# helper to quickly configure project

cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DTHH_PACKED_HASHTABLE_ENABLE_MEMORY=ON \
-DTHH_PACKED_HASHTABLE_ENABLE_TEST=ON \
-DTHH_PACKED_HASHTABLE_ENABLE_BENCH=ON
